//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecomm19032025.AdminManage
{
    public partial class OrderList
    {
        protected global::System.Web.UI.WebControls.Repeater RptOrders;
    }
}
