//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecomm19032025.AdminManage
{
    public partial class UserAddEdit
    {
        protected global::System.Web.UI.WebControls.TextBox TxtFname;
        protected global::System.Web.UI.WebControls.TextBox TxtEmail;
        protected global::System.Web.UI.WebControls.TextBox TxtPass;
        protected global::System.Web.UI.WebControls.TextBox TxtAddress;
        protected global::System.Web.UI.WebControls.TextBox TxtPhone;
        protected global::System.Web.UI.WebControls.HiddenField HidUid;
        protected global::System.Web.UI.WebControls.Button BtnSave;
    }
}
